apiVersion: v1
kind: Template
labels:
  template: letsencrypt
metadata:
  annotations:
    description: Provides a webserver for downloading letsencrypt certificates
    iconClass: icon-globe
    tags: tls,letsencrypt,http
  creationTimestamp: null
  name: letsencrypt
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: letsencrypt
- apiVersion: v1
  kind: Service
  metadata:
    name: web-service
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      name: letsencrypt
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: letsencypt
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: letsencrypt:latest
    source:
      contextDir: ${GIT_CONTEXT_DIR}
      git:
        ref: ${GIT_REPOSITORY_REF}
        uri: ${GIT_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy: null
      type: Docker
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
- description: The URL of the repository containing the kiosk Dockerfiles
  displayName: Kiosk git Repo
  name: GIT_REPOSITORY_URL
  required: true
  value: https://github.com/kevensen/letsencrypt-container.git
- description: The repository reference for the Dockerfile
  displayName: Dockerfile Repoistory Branch
  name: GIT_REPOSITORY_REF
  required: true
  value: master
- description: Set this to the subdirectory containing the Dockerfile
  displayName: Dockerfile Context Directory
  name: GIT_CONTEXT_DIR
  required: false
- description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
