apiVersion: v1
kind: Template
labels:
  template: letsencrypt-job
metadata:
  annotations:
    description: Provides a webserver for downloading letsencrypt certificates
    iconClass: icon-python
    tags: tls,letsencrypt,http
  creationTimestamp: null
  name: letsencrypt-job
objects:

- apiVersion: v1
  kind: Route
  metadata:
    name: letsencrypt
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: letsencrypt
- apiVersion: v1
  kind: Service
  metadata:
    name: letsencrypt
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      name: letsencrypt

- apiVersion: batch/v1
  kind: Job
  metadata:
    name: letsencrypt
  spec:
    parallelism: 1    
    completions: 1    
    template:         
      metadata:
        name: letsencrypt
      spec:
        env:
        - name: APPLICATION_DOMAIN
          value: ${APPLICATION_DOMAIN}
        containers:
        - name: certbot
          image: letsencrypt
          command: ["certbot/bin/activate",  "&&, "certbot", "certonly", "--standalone", $APPLICATION_DOMAIN]
        restartPolicy: OnFailure 
parameters:

- description: The exposed hostname that will route to the CakePHP service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
